language: python
sudo: required
dist: xenial
services:
  - postgresql
python:
  - 3.8
before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - pipenv run python -m pip install -U pip
  - pipenv install --dev --ignore-pipfile
before_script:
  - cp config/settings/.ccb.env config/settings/ccb.env
  - psql -c "CREATE DATABASE ccb;" -U postgres
  - psql -c "CREATE USER ccb WITH PASSWORD 'ccb';" -U postgres
  - psql -c "ALTER ROLE ccb SET client_encoding TO 'utf8';" -U postgres
  - psql -c "ALTER ROLE ccb SET default_transaction_isolation TO 'read committed';" -U postgres
  - psql -c "ALTER ROLE ccb SET timezone TO 'UTC';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ccb TO ccb;" -U postgres
  - psql -c "ALTER USER ccb CREATEDB;" -U postgres
  - pipenv run python manage.py collectstatic --no-input
script:
  # Run Tests
  - ./cc-test-reporter before-build
  - pipenv run pytest --cov ccb --cov-report xml
  # Run Linters
  - pipenv run pylint ccb/ config/ --ignore=tests
  #- |
  #  pipenv run pylint users/tests --min-similarity-lines=20
  - pipenv run pycodestyle ccb/ config/
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
